/* ===========================================================================
   LEAN APP · Onboarding — DADOS
   Conteúdo do manual operacional + telas reais do painel administrativo.
   =========================================================================== */
(function () {
  const F = (o) => o;

  const FEATURES = [
    /* ===================== PAINÉIS ===================== */
    F({
      id: 'dashboard', name: 'Principal', sub: 'Dashboard',
      group: 'Painéis', journey: 'acompanhar', role: 'Gestor', level: 'Essencial',
      lead: 'Visão geral e em tempo real do desempenho da loja — o ponto de partida do dia a dia.',
      oque: 'Tela inicial do painel administrativo. Reúne os principais indicadores da operação: receita, ticket médio, pedidos, evolução, produtos em destaque e histórico de pedidos.',
      quando: 'Diariamente, para acompanhar o status dos pedidos, identificar tendências de vendas e verificar os produtos de maior destaque.',
      beneficios: ['Tomada de decisão rápida e informada', 'Identificação de oportunidades no catálogo', 'Panorama completo da operação em uma só tela'],
      prereq: ['Acesso ao painel administrativo do Lean App.'],
      configurar: ['Não há configuração direta — os dados são agregados automaticamente.', 'Ajuste o filtro de período (Hoje, Ontem, 7 dias, 30 dias) no topo direito.'],
      utilizar: ['Ao acessar o painel, o dashboard é a primeira tela exibida.', 'Use os filtros de período para recortar a visualização.', 'Analise evolução de pedidos, performance por plataforma e produtos mais vendidos.'],
      praticas: ['Verifique o dashboard no início e no fim do dia.', 'Use os dados para planejar ações de marketing e estoque.'],
      erros: ['Interpretar um dia isolado sem considerar a sazonalidade.', 'Ignorar o período de comparação ao ler as variações.'],
      faq: [{ q: 'Os dados são em tempo real?', a: 'Sim, são atualizados continuamente.' }],
      kpis: ['Receita', 'Ticket médio', 'Pedidos', 'Itens por pedido'],
      responsavel: 'Gerente de e-commerce · Analista de Vendas',
      imgs: [{ src: 'dashboard.png', cap: 'Dashboard com filtros de período, evolução de pedidos, performance por plataforma e histórico.' }],
    }),
    F({
      id: 'performance', name: 'Performance',
      group: 'Painéis', journey: 'acompanhar', role: 'Marketing', level: 'Intermediário',
      lead: 'Análise aprofundada de tráfego, engajamento e conversão, segmentada por canal.',
      oque: 'Módulo dedicado a métricas estratégicas, organizado em três abas: Analytics (sessões e engajamento), Conversões (taxas por etapa) e Vendas (receita por canal).',
      quando: 'Em análises estratégicas de marketing, avaliação de campanhas e otimização da jornada de compra.',
      beneficios: ['Insights detalhados sobre o comportamento do usuário', 'Avaliação da eficácia das campanhas', 'Comparação de desempenho entre canais (Android, iOS, Site)'],
      prereq: ['Acesso ao painel administrativo.'],
      configurar: ['Os dados são coletados automaticamente.', 'Use o botão Filtros para definir período e período de comparação.'],
      utilizar: ['Navegue até Performance.', 'Alterne entre as abas Analytics, Conversões e Vendas.', 'Segmente por canal e compare períodos para identificar tendências.'],
      praticas: ['Compare sempre contra o período anterior.', 'Cruze métricas de funil em vez de olhar uma isolada.'],
      erros: ['Focar em uma métrica única fora do contexto do funil.', 'Comparar períodos de tamanhos diferentes.'],
      faq: [{ q: 'Posso comparar dois períodos?', a: 'Sim. No painel de Filtros há período principal e período de comparação.' }],
      kpis: ['Taxa de conversão', 'Sessões', 'Engajamento', 'Receita por canal'],
      responsavel: 'Analista de Marketing · Product Owner',
      imgs: [
        { src: 'performance-analytics.png', cap: 'Aba Analytics — sessões, engajamento, usuários ativos e novos cadastros.' },
        { src: 'performance-conversoes.png', cap: 'Aba Conversões — taxas de sessão, jornada e checkout por canal.' },
        { src: 'performance-vendas.png', cap: 'Aba Vendas — receita, ticket médio e pedidos por canal.' },
        { src: 'performance-filtros.png', cap: 'Painel de Filtros — período e período de comparação.' },
      ],
    }),

    /* ===================== MARKETING ===================== */
    F({
      id: 'vitrines', name: 'Vitrines',
      group: 'Marketing', journey: 'operar', role: 'Marketing', level: 'Essencial',
      lead: 'Banners e destaques visuais do app — o principal canal de campanhas e promoções.',
      oque: 'Gerencia as vitrines de banners exibidas no aplicativo, com componentes (mídias, produtos, espaçadores) e preview em tempo real do celular.',
      quando: 'Para promover produtos, anunciar ofertas, comunicar novidades ou direcionar o usuário a seções relevantes.',
      beneficios: ['Aumenta a visibilidade de produtos e promoções', 'Melhora a experiência de compra', 'Impulsiona vendas de itens estratégicos'],
      prereq: ['Imagens dos banners prontas.', 'Período de validade da campanha definido.'],
      configurar: ['Acesse Marketing › Vitrines e clique em Adicionar.', 'Preencha título, datas de início e término e ative.', 'Em Componentes, clique em Adicionar e escolha o tipo (Simples, Carrossel, Grade, Lista…).', 'Acompanhe o resultado no preview do celular.'],
      utilizar: ['Ative/desative vitrines pela coluna Ativo na listagem.', 'Edite ou exclua pelas ações da linha.', 'Atualize regularmente para manter o conteúdo relevante.'],
      praticas: ['Use imagens de alta qualidade e validade clara.', 'Teste diferentes layouts de componente.'],
      erros: ['Banners desatualizados ou com validade vencida.', 'Imagens de baixa resolução.'],
      faq: [{ q: 'Posso agendar uma vitrine?', a: 'Sim, definindo as datas de início e término.' }, { q: 'Quantos componentes posso adicionar?', a: 'Vários — combine mídias e listas de produtos para montar a vitrine.' }],
      kpis: ['CTR dos banners', 'Vendas de produtos promovidos'],
      responsavel: 'Analista de Marketing · Designer',
      imgs: [
        { src: 'vitrines.png', cap: 'Listagem de vitrines com status (Publicado/Inativo) e validade.' },
        { src: 'vitrines-configurar.png', cap: 'Edição da vitrine — título, datas, componentes e preview do app.' },
        { src: 'vitrines-componentes.png', cap: 'Seleção de componentes: mídias, produtos e espaçadores.' },
      ],
    }),
    F({
      id: 'hotsites', name: 'Hotsites',
      group: 'Marketing', journey: 'operar', role: 'Marketing', level: 'Intermediário',
      lead: 'Páginas de destino personalizadas dentro do app para campanhas específicas.',
      oque: 'Ferramenta para criar vitrines de banners alternativas — páginas temáticas dedicadas a campanhas, lançamentos ou conteúdos especiais, montadas por componentes.',
      quando: 'Para campanhas que exigem uma página dedicada, sem criar uma nova seção no aplicativo.',
      beneficios: ['Experiências personalizadas por campanha', 'Direciona tráfego para conteúdos específicos', 'Aumenta a conversão de ações de marketing'],
      prereq: ['Conteúdo (imagens, produtos) e estrutura da página definidos.'],
      configurar: ['Acesse Marketing › Hotsites e clique em Adicionar.', 'Informe o título e ative.', 'Em Componentes, adicione mídias e listas de produtos.', 'Salve e acompanhe pelo preview.'],
      utilizar: ['Ative/desative na listagem.', 'Divulgue o hotsite em campanhas (vitrines, push, redes).'],
      praticas: ['Carregamento rápido e chamadas de ação claras.', 'Mantenha links e conteúdo atualizados.'],
      erros: ['Conteúdo desatualizado ou links quebrados.', 'Layout não otimizado para mobile.'],
      faq: [{ q: 'Qual a diferença para Vitrines?', a: 'Hotsites são páginas temáticas independentes; vitrines ficam na home do app.' }],
      kpis: ['Conversão do hotsite', 'Engajamento'],
      responsavel: 'Analista de Marketing · Designer',
      imgs: [
        { src: 'hotsites.png', cap: 'Listagem de hotsites.' },
        { src: 'hotsites-adicionar.png', cap: 'Edição do hotsite com componentes e preview.' },
        { src: 'hotsites-componentes.png', cap: 'Biblioteca de componentes do hotsite.' },
      ],
    }),

    /* ===================== CONFIGURAÇÕES DA LOJA ===================== */
    F({
      id: 'categorias', name: 'Categorias',
      group: 'Configurações da Loja', journey: 'configurar', role: 'E-commerce', level: 'Essencial',
      lead: 'Organização hierárquica do catálogo — a base da navegação do app.',
      oque: 'Sistema de categorias e subcategorias que estrutura o catálogo e define como o usuário navega e encontra produtos.',
      quando: 'Para estruturar o catálogo, facilitar a busca e melhorar a navegação.',
      beneficios: ['Usabilidade e descoberta de produtos', 'Catálogo organizado', 'Maior conversão ao guiar o usuário'],
      prereq: ['Conhecimento da estrutura do catálogo.'],
      configurar: ['Acesse Configurações da Loja › Categorias e clique em Adicionar.', 'Escolha a categoria pai (se for subcategoria), informe o título e a ação.', 'Defina a ordenação do catálogo e salve.'],
      utilizar: ['Ative/desative categorias na listagem.', 'Mantenha a árvore atualizada conforme o catálogo evolui.'],
      praticas: ['Estrutura lógica e fácil de entender.', 'Evite categorias genéricas ou específicas demais.'],
      erros: ['Categorias duplicadas ou mal organizadas.', 'Produtos sem categoria atribuída.'],
      faq: [{ q: 'Posso criar vários níveis?', a: 'Sim — categorias, subcategorias e níveis seguintes (ex.: Cabelos › Acessórios › Aplicadores).' }],
      kpis: ['Tempo de navegação', 'Taxa de conversão'],
      responsavel: 'Gerente de E-commerce · UX',
      imgs: [
        { src: 'categorias.png', cap: 'Árvore de categorias com ativação por linha.' },
        { src: 'categorias-adicionar.png', cap: 'Cadastro de categoria — pai, título, ação e ordenação.' },
      ],
    }),
    F({
      id: 'p-especificacoes', name: 'Especificações de Produto', sub: 'Produtos',
      group: 'Configurações da Loja', journey: 'configurar', role: 'E-commerce', level: 'Intermediário',
      lead: 'Atributos técnicos e descritivos dos produtos (material, descrição, cor…).',
      oque: 'Define e gerencia as especificações exibidas na página do produto e usadas em filtros de busca.',
      quando: 'Ao cadastrar novos produtos ou enriquecer informações de produtos existentes.',
      beneficios: ['Informação completa para o cliente', 'Menos dúvidas e devoluções', 'Melhor relevância nas buscas'],
      prereq: ['Conhecimento das características de cada produto.'],
      configurar: ['Acesse Produtos › Especificações de Produto e clique em Adicionar.', 'Informe o título (ex.: Descrição) e o tipo (texto, número, seleção).', 'Selecione as categorias que exibirão a especificação e salve.'],
      utilizar: ['Garanta que todos os produtos tenham as especificações preenchidas.', 'Use-as para criar filtros avançados.'],
      praticas: ['Padronize as especificações entre produtos.', 'Evite especificações redundantes.'],
      erros: ['Especificações incompletas ou inconsistentes.', 'Erros de digitação.'],
      faq: [{ q: 'Posso personalizar por tipo de produto?', a: 'Sim, associando cada especificação às categorias certas.' }],
      kpis: ['Tempo na página do produto', 'Conversão'],
      responsavel: 'Analista de Produtos',
      imgs: [
        { src: 'especificacoes.png', cap: 'Listagem de especificações.' },
        { src: 'especificacoes-adicionar.png', cap: 'Cadastro — título, tipo e categorias associadas.' },
      ],
    }),
    F({
      id: 'p-grades', name: 'Grades', sub: 'Produtos',
      group: 'Configurações da Loja', journey: 'configurar', role: 'E-commerce', level: 'Intermediário',
      lead: 'Variações de produto (tamanho, cor, voltagem) exibidas corretamente no app.',
      oque: 'Configura as grades de variação dos produtos — atributo, tipo do atributo, tipo da grade (texto/imagem) e ordenação.',
      quando: 'Para produtos com múltiplas opções que o cliente escolhe (tamanho, cor, voltagem).',
      beneficios: ['Seleção clara da variação desejada', 'Catálogo organizado', 'Evita duplicação de produtos'],
      prereq: ['Produtos com variações definidas.'],
      configurar: ['Acesse Produtos › Grades e clique em Adicionar.', 'Informe o atributo (ex.: Tamanho, Cor) e o tipo do atributo e da grade.', 'Defina a ordenação e as categorias de produtos que exibirão a grade.'],
      utilizar: ['Confira a exibição das grades no app.', 'Use o toggle Principal para a grade prioritária.'],
      praticas: ['Nomes claros e consistentes para os atributos.', 'Teste a seleção de variações no app.'],
      erros: ['Variações ausentes ou incorretas.', 'Problemas na exibição das opções.'],
      faq: [{ q: 'Posso ter mais de uma grade no produto?', a: 'Sim — por exemplo Tamanho e Cor simultaneamente.' }],
      kpis: ['Conversão', 'Redução de devoluções'],
      responsavel: 'Analista de Produtos',
      imgs: [
        { src: 'grades.png', cap: 'Grades cadastradas — atributo, tipos e ordenação.' },
        { src: 'grades-adicionar.png', cap: 'Cadastro de grade com categorias associadas.' },
      ],
    }),
    F({
      id: 'p-etiquetas', name: 'Etiquetas', sub: 'Produtos',
      group: 'Configurações da Loja', journey: 'operar', role: 'Marketing', level: 'Básico',
      lead: 'Marcadores de campanha exibidos no card do produto (ex.: “Leve 2 por R$…”).',
      oque: 'Cria etiquetas (texto ou imagem) aplicadas a coleções de produtos para destacar campanhas e aumentar a visibilidade.',
      quando: 'Para sinalizar promoções, condições especiais ou destaques no catálogo.',
      beneficios: ['Mais visibilidade para campanhas', 'Comunicação rápida da oferta', 'Filtragem e segmentação'],
      prereq: ['Definição das etiquetas e coleções-alvo.'],
      configurar: ['Acesse Produtos › Etiquetas e clique em Adicionar.', 'Escolha o tipo, informe o título e (se houver) imagem e validade.', 'Selecione as coleções que exibirão a etiqueta e salve.'],
      utilizar: ['Ative/desative na listagem.', 'Acompanhe a pré-visualização da etiqueta.'],
      praticas: ['Conjunto enxuto e consistente de etiquetas.', 'Respeite a validade das campanhas.'],
      erros: ['Etiquetas em excesso poluindo a interface.', 'Etiquetas vencidas ainda ativas.'],
      faq: [{ q: 'Etiqueta é o mesmo que selo?', a: 'Não. Etiquetas costumam ser textuais na vitrine/card; selos são marcadores visuais sobre o produto.' }],
      kpis: ['CTR em produtos com etiqueta'],
      responsavel: 'Analista de Marketing',
      imgs: [
        { src: 'etiquetas.png', cap: 'Etiquetas com pré-visualização e status.' },
        { src: 'etiquetas-adicionar.png', cap: 'Cadastro de etiqueta com coleções e preview no app.' },
      ],
    }),
    F({
      id: 'p-selos', name: 'Selos', sub: 'Produtos',
      group: 'Configurações da Loja', journey: 'operar', role: 'Marketing', level: 'Básico',
      lead: 'Elementos visuais sobre o produto (Frete Grátis, Outlet, Clube…).',
      oque: 'Cria selos (imagem) posicionados sobre o produto para destacar status e condições especiais.',
      quando: 'Para chamar atenção a produtos estratégicos, promoções ou status relevantes.',
      beneficios: ['Destaque visual imediato', 'Comunica condições importantes', 'Impulsiona vendas de itens específicos'],
      prereq: ['Imagens dos selos e posição de exibição definidas.'],
      configurar: ['Acesse Produtos › Selos e clique em Adicionar.', 'Defina tipo, posição e título; faça upload da imagem e a validade.', 'Selecione as coleções que exibirão o selo e salve.'],
      utilizar: ['Ative/desative na listagem.', 'Acompanhe a pré-visualização no card.'],
      praticas: ['Use selos com parcimônia para não poluir.', 'Garanta selos visualmente atraentes.'],
      erros: ['Excesso de selos confunde o cliente.', 'Selos desatualizados ou enganosos.'],
      faq: [{ q: 'Posso personalizar o selo?', a: 'Sim, via upload de imagem, com posição e validade configuráveis.' }],
      kpis: ['CTR em produtos com selo', 'Vendas de itens destacados'],
      responsavel: 'Analista de Marketing · Designer',
      imgs: [
        { src: 'selos.png', cap: 'Selos com posição, validade e pré-visualização.' },
        { src: 'selos-adicionar.png', cap: 'Cadastro — tipo, posição, imagem, coleções e preview.' },
      ],
    }),
    F({
      id: 'p-recomendacoes', name: 'Recomendações de Produtos', sub: 'Produtos',
      group: 'Configurações da Loja', journey: 'operar', role: 'Marketing', level: 'Intermediário',
      lead: 'Vitrines de produtos sugeridos para aumentar ticket médio e descoberta.',
      oque: 'Configura blocos de recomendação na página do produto (ex.: “Quem viu, também viu”) integrados a plataformas como VTEX e Linx.',
      quando: 'Para sugerir produtos complementares/alternativos e incentivar compras adicionais.',
      beneficios: ['Aumenta o ticket médio', 'Oferta mais relevante', 'Maior tempo no app'],
      prereq: ['Plataforma de recomendação integrada (ex.: VTEX, Linx).'],
      configurar: ['Acesse Produtos › Recomendações de Produtos e clique em Adicionar.', 'Selecione a plataforma e o tipo (ex.: “Quem comprou, também comprou”).', 'Informe título e subtítulo e salve.'],
      utilizar: ['Ative/desative cada recomendação.', 'Monitore cliques e conversão dos blocos.'],
      praticas: ['Combine tipos de recomendação.', 'Evite recomendar itens fora de estoque.'],
      erros: ['Recomendações irrelevantes ou repetitivas.', 'Produtos indisponíveis sendo sugeridos.'],
      faq: [{ q: 'De onde vêm as recomendações?', a: 'Da plataforma integrada (VTEX, Linx etc.) conforme o tipo escolhido.' }],
      kpis: ['Ticket médio', 'Conversão'],
      responsavel: 'Analista de Marketing · Dados',
      imgs: [
        { src: 'recomendacoes.png', cap: 'Recomendações por plataforma e tipo.' },
        { src: 'recomendacoes-adicionar.png', cap: 'Cadastro — plataforma, tipo, título e subtítulo.' },
      ],
    }),
    F({
      id: 'p-restricoes', name: 'Restrições de Vendas', sub: 'Produtos',
      group: 'Configurações da Loja', journey: 'configurar', role: 'E-commerce', level: 'Avançado',
      lead: 'Regras que limitam a venda de produtos por critérios específicos.',
      oque: 'Define regras de restrição (por coleção, região, etc.) com tipo, ação e período de aplicação.',
      quando: 'Para conformidade legal, gestão de estoque ou políticas comerciais específicas.',
      beneficios: ['Conformidade legal', 'Evita vendas indevidas', 'Estratégias de venda controladas'],
      prereq: ['Definição clara das regras de restrição.'],
      configurar: ['Acesse Produtos › Restrições de Vendas e clique em Adicionar.', 'Informe título, datas e o tipo de restrição (ex.: Coleção de produtos).', 'Selecione as coleções e a ação e salve.'],
      utilizar: ['Ative/desative as regras.', 'Revise periodicamente para manter a conformidade.'],
      praticas: ['Documente cada regra e seu motivo.', 'Teste cenários para evitar bloqueios indevidos.'],
      erros: ['Restrições que bloqueiam vendas legítimas.', 'Falha em aplicar restrições necessárias.'],
      faq: [{ q: 'Posso aplicar a grupos de produtos?', a: 'Sim — selecionando as coleções que exibirão a restrição.' }],
      kpis: ['Conformidade legal', 'Gestão de estoque'],
      responsavel: 'Gerente de E-commerce · Jurídico',
      imgs: [
        { src: 'restricoes.png', cap: 'Listagem de restrições de venda.' },
        { src: 'restricoes-adicionar.png', cap: 'Cadastro — tipo, ação, período e coleções.' },
      ],
    }),
    F({
      id: 'assinaturas', name: 'Assinaturas',
      group: 'Configurações da Loja', journey: 'configurar', role: 'E-commerce', level: 'Avançado',
      lead: 'Planos de assinatura com cobrança recorrente e benefícios exclusivos.',
      oque: 'Gerencia planos de assinatura (Lista) e as opções gerais da funcionalidade (Configurações), com identificador e benefícios ativos por plano.',
      quando: 'Para oferecer produtos/serviços recorrentes, clubes ou benefícios contínuos.',
      beneficios: ['Receita recorrente (MRR)', 'Fidelização de clientes', 'Compra simplificada para itens contínuos'],
      prereq: ['Produtos/serviços configurados para o modelo de assinatura.'],
      configurar: ['Acesse Configurações da Loja › Assinaturas.', 'Na aba Configurações, ative a funcionalidade.', 'Na aba Lista, clique em Adicionar e defina título, identificador e benefícios.'],
      utilizar: ['Ative/desative planos pela listagem.', 'Acompanhe a base de assinantes e o churn.'],
      praticas: ['Deixe claros preço, frequência e cancelamento.', 'Ofereça benefícios de valor real.'],
      erros: ['Dificultar o cancelamento.', 'Cobranças inesperadas.'],
      faq: [{ q: 'Posso ter vários planos?', a: 'Sim — ex.: Padrão, Fraldas, Skincare, cada um com seus benefícios.' }],
      kpis: ['MRR', 'Retenção', 'LTV'],
      responsavel: 'Gerente de E-commerce · Atendimento',
      imgs: [
        { src: 'assinaturas.png', cap: 'Lista de planos com identificador e benefícios ativos.' },
        { src: 'assinaturas-config.png', cap: 'Aba Configurações — ativa a funcionalidade de assinatura.' },
        { src: 'assinaturas-adicionar.png', cap: 'Cadastro de plano — título, identificador e benefícios.' },
      ],
    }),
    F({
      id: 'integracoes', name: 'Integrações',
      group: 'Configurações da Loja', journey: 'configurar', role: 'TI', level: 'Avançado',
      lead: 'Conexões com serviços externos (pagamento, analytics, logística, busca…).',
      oque: 'Catálogo de integrações que conectam o Lean App a sistemas externos — cada card mostra a categoria, o status (Habilitado/Desabilitado) e a edição.',
      quando: 'Para automatizar processos, sincronizar dados e ampliar funcionalidades do app.',
      beneficios: ['Menos trabalho manual e erros', 'Eficiência operacional', 'Visão unificada do negócio'],
      prereq: ['Credenciais de acesso aos sistemas externos.'],
      configurar: ['Acesse Configurações da Loja › Integrações.', 'Localize o serviço (ex.: Adyen, Google Analytics, Intelipost) e clique em Editar.', 'Informe as credenciais e habilite a integração.'],
      utilizar: ['Monitore o status de cada integração.', 'Teste em homologação antes de produção.'],
      praticas: ['Mantenha credenciais seguras.', 'Documente o fluxo de dados entre sistemas.'],
      erros: ['Falhas de sincronização.', 'Erros de autenticação.'],
      faq: [{ q: 'Quais sistemas posso integrar?', a: 'Pagamento, analytics, logística, busca, mídia e avaliações. Consulte o time Leanwork para o catálogo atualizado.' }],
      kpis: ['Eficiência operacional', 'Precisão dos dados'],
      responsavel: 'TI · Analista de Sistemas',
      imgs: [
        { src: 'integracoes.png', cap: 'Catálogo de integrações por categoria e status.' },
        { src: 'integracoes-wake.png', cap: 'Conjunto de integrações de pagamento e mídia.' },
      ],
    }),
    F({
      id: 'c-gerais', name: 'Configurações Gerais', sub: 'Configurações',
      group: 'Configurações da Loja', journey: 'configurar', role: 'E-commerce', level: 'Intermediário',
      lead: 'Central de ajustes do app: catálogo, checkout, cupons, favoritos, produto, notificações e regionalização.',
      oque: 'Conjunto de configurações que controlam o comportamento e a aparência das funcionalidades do app, organizado por abas laterais.',
      quando: 'Para personalizar a experiência, otimizar o fluxo de compra e adaptar o app às políticas da loja.',
      beneficios: ['Alto grau de customização sem desenvolvimento', 'Melhor usabilidade', 'Controle fino das funcionalidades'],
      prereq: ['Definição das políticas e preferências da loja.'],
      configurar: ['Acesse Configurações › Configurações Gerais.', 'Navegue pelas abas (Catálogo, Checkout, Cupons, Favoritos, Produto, Notificações, Regionalização).', 'Ajuste os parâmetros e clique em Atualizar.'],
      utilizar: ['Revise as configurações periodicamente.', 'Teste alterações antes de publicar.'],
      praticas: ['Documente as alterações feitas.', 'Entenda o impacto de cada ajuste na experiência.'],
      erros: ['Configurações conflitantes.', 'Publicar sem testar.'],
      faq: [{ q: 'As mudanças valem na hora?', a: 'Após Atualizar, os ajustes são aplicados ao app conforme a propagação.' }],
      kpis: ['Conversão', 'Satisfação do cliente'],
      responsavel: 'Gerente de E-commerce · Marketing',
      imgs: [
        { src: 'config-catalogo.png', cap: 'Catálogo — API de produto/busca e ordenação padrão.' },
        { src: 'config-checkout.png', cap: 'Checkout — carrinho, entrega e pagamento.' },
        { src: 'config-cupons.png', cap: 'Cupons — disponibilidade por seção.' },
        { src: 'config-favoritos.png', cap: 'Favoritos — ativa a funcionalidade.' },
        { src: 'config-produto.png', cap: 'Produto — avaliações, kit, últimas unidades e marketplace.' },
        { src: 'config-notificacoes.png', cap: 'Notificações — webhook de status do pedido.' },
        { src: 'config-regionalizacao.png', cap: 'Regionalização — onboarding e obrigatoriedade.' },
      ],
    }),
    F({
      id: 'c-versao', name: 'Controle de Versão', sub: 'Configurações',
      group: 'Configurações da Loja', journey: 'acompanhar', role: 'TI', level: 'Básico',
      lead: 'Distribuição controlada das versões do app (Android/iOS, obrigatório ou não).',
      oque: 'Gerencia as versões publicadas do aplicativo — número (major.minor.patch), plataformas e se a atualização é obrigatória.',
      quando: 'Para acompanhar o ciclo de vida do app e controlar a adoção de novas versões.',
      beneficios: ['Transparência sobre atualizações', 'Distribuição controlada', 'Apoio ao suporte ao cliente'],
      prereq: ['N/A — registrado pelo sistema/equipe.'],
      configurar: ['Acesse Configurações › Controle de Versão e clique em Adicionar.', 'Informe major, minor e patch e marque Android/iOS.', 'Defina se é obrigatório e ative.'],
      utilizar: ['Consulte o histórico de versões.', 'Use para apoiar o suporte em dúvidas por versão.'],
      praticas: ['Registre o que mudou em cada versão.', 'Comunique atualizações relevantes aos usuários.'],
      erros: ['Não documentar mudanças de versão.', 'Forçar atualização sem necessidade.'],
      faq: [{ q: 'Posso forçar a atualização?', a: 'Sim, marcando a versão como obrigatória.' }],
      kpis: ['Adoção de versões', 'Tempo de resolução de suporte'],
      responsavel: 'TI · Atendimento',
      imgs: [
        { src: 'controle-versao.png', cap: 'Histórico de versões por plataforma e obrigatoriedade.' },
        { src: 'controle-versao-adicionar.png', cap: 'Cadastro — major/minor/patch e plataformas.' },
      ],
    }),
    F({
      id: 'c-redes', name: 'Redes Sociais', sub: 'Configurações',
      group: 'Configurações da Loja', journey: 'configurar', role: 'Marketing', level: 'Básico',
      lead: 'Links das redes sociais da loja exibidos no app.',
      oque: 'Configura os perfis de redes sociais (Facebook, Instagram, Pinterest, TikTok, Twitter, YouTube) exibidos no aplicativo.',
      quando: 'Para fortalecer a presença da marca e direcionar tráfego aos perfis.',
      beneficios: ['Mais alcance da marca', 'Maior engajamento', 'Tráfego cruzado entre canais'],
      prereq: ['Perfis ativos nas redes.'],
      configurar: ['Acesse Configurações › Redes Sociais e ative.', 'Informe o usuário/handle de cada rede ao lado do domínio.', 'Clique em Salvar.'],
      utilizar: ['Mantenha os links atualizados.', 'Use as redes para divulgar novidades.'],
      praticas: ['Integre apenas as redes relevantes ao público.', 'Verifique se os links funcionam.'],
      erros: ['Links quebrados.', 'Perfis desatualizados.'],
      faq: [{ q: 'Preciso preencher todas?', a: 'Não — preencha apenas as redes que a loja usa.' }],
      kpis: ['Engajamento social', 'Tráfego para o app'],
      responsavel: 'Analista de Marketing · Social Media',
      imgs: [{ src: 'redes-sociais.png', cap: 'Configuração dos perfis sociais por rede.' }],
    }),
    F({
      id: 'c-institucionais', name: 'Páginas Institucionais', sub: 'Configurações',
      group: 'Configurações da Loja', journey: 'configurar', role: 'Atendimento', level: 'Básico',
      lead: 'Conteúdo estático: Sobre, Política de Privacidade, Termos, Fale Conosco…',
      oque: 'Cria e edita páginas de conteúdo institucional exibidas no app, com título e URL.',
      quando: 'Para fornecer informações da empresa, políticas e termos legais.',
      beneficios: ['Confiança e transparência', 'Conformidade legal', 'Menos dúvidas no suporte'],
      prereq: ['Conteúdo das páginas pronto.'],
      configurar: ['Acesse Configurações › Páginas Institucionais e clique em Adicionar.', 'Informe título e conteúdo/URL.', 'Ative para exibir no app.'],
      utilizar: ['Mantenha o conteúdo legal atualizado.', 'Garanta fácil acesso no app.'],
      praticas: ['Linguagem clara e objetiva.', 'Revisão periódica do conteúdo.'],
      erros: ['Conteúdo desatualizado.', 'Páginas difíceis de encontrar.'],
      faq: [{ q: 'Quais páginas criar primeiro?', a: 'Comece por Fale Conosco, Política de Privacidade e Termos de Uso.' }],
      kpis: ['Conformidade', 'Redução de dúvidas'],
      responsavel: 'Jurídico · Marketing',
      imgs: [{ src: 'paginas-institucionais.png', cap: 'Listagem de páginas institucionais com URL.' }],
    }),
    F({
      id: 'c-servico', name: 'Páginas de Serviço', sub: 'Configurações',
      group: 'Configurações da Loja', journey: 'configurar', role: 'Atendimento', level: 'Básico',
      lead: 'Páginas de autoatendimento: FAQ, Atendimento, Avalie o app…',
      oque: 'Cria páginas de suporte e serviço (com ícone e tipo de ação) exibidas no aplicativo.',
      quando: 'Para oferecer autoatendimento e responder dúvidas comuns.',
      beneficios: ['Menos chamados de suporte', 'Respostas rápidas ao cliente', 'Experiência mais fluida'],
      prereq: ['Conteúdo das páginas de serviço pronto.'],
      configurar: ['Acesse Configurações › Páginas de Serviço e clique em Adicionar.', 'Informe título, tipo de ação e ícone.', 'Ative para exibir no app.'],
      utilizar: ['Mantenha o conteúdo alinhado às dúvidas frequentes.', 'Promova as páginas como fonte de autoatendimento.'],
      praticas: ['Organize de forma clara e navegável.', 'Use perguntas e respostas (FAQ).'],
      erros: ['Conteúdo confuso ou incompleto.', 'Páginas difíceis de encontrar.'],
      faq: [{ q: 'Que páginas incluir?', a: 'Atendimento ao cliente, Institucional e Avalie nosso aplicativo são bons pontos de partida.' }],
      kpis: ['Redução de chamados', 'Satisfação'],
      responsavel: 'Atendimento · Marketing',
      imgs: [
        { src: 'paginas-servico.png', cap: 'Páginas de serviço ativas.' },
        { src: 'paginas-servico-adicionar.png', cap: 'Cadastro — título, tipo de ação e ícone.' },
      ],
    }),
    F({
      id: 'c-suporte', name: 'Suporte', sub: 'Configurações',
      group: 'Configurações da Loja', journey: 'configurar', role: 'Atendimento', level: 'Básico',
      lead: 'Canais de atendimento exibidos no app (e-mail, telefone, WhatsApp).',
      oque: 'Configura os canais de suporte (aba Canais) e o botão de WhatsApp (aba WhatsApp), com mensagem pré-definida.',
      quando: 'Para garantir acesso fácil e rápido aos canais de atendimento da loja.',
      beneficios: ['Mais satisfação e confiança', 'Resolução eficiente de problemas', 'Fidelização'],
      prereq: ['Canais de atendimento ativos.'],
      configurar: ['Acesse Configurações › Suporte.', 'Na aba Canais, informe e-mail, telefone, WhatsApp e horário.', 'Na aba WhatsApp, ative a exibição e a mensagem pré-definida e salve.'],
      utilizar: ['Mantenha contatos atualizados.', 'Monitore tempo de resposta dos canais.'],
      praticas: ['Ofereça múltiplos canais.', 'Treine a equipe de atendimento.'],
      erros: ['Contatos desatualizados.', 'Canais indisponíveis.'],
      faq: [{ q: 'Posso exibir o WhatsApp na home e no produto?', a: 'Sim — há toggles para a página inicial e a página de produto.' }],
      kpis: ['Satisfação', 'Tempo de resolução'],
      responsavel: 'Atendimento · Gerente de E-commerce',
      imgs: [
        { src: 'suporte-canais.png', cap: 'Canais — e-mail, telefone, WhatsApp e horário.' },
        { src: 'suporte-whatsapp.png', cap: 'WhatsApp — exibição e mensagem pré-definida.' },
      ],
    }),

    /* ===================== CONTROLE DE ACESSO ===================== */
    F({
      id: 'usuarios', name: 'Usuários',
      group: 'Controle de Acesso', journey: 'configurar', role: 'TI', level: 'Essencial',
      lead: 'Quem acessa o painel e com quais permissões.',
      oque: 'Gerencia os usuários do painel administrativo — ativo, perfil de administrador, relatório semanal, nome e e-mail.',
      quando: 'Para conceder/revogar acesso e atribuir permissões à equipe.',
      beneficios: ['Segurança dos dados', 'Delegação controlada de tarefas', 'Gestão clara da equipe'],
      prereq: ['Papéis e responsabilidades definidos.'],
      configurar: ['Acesse Controle de Acesso › Usuários e clique em Adicionar.', 'Informe nome e e-mail e defina Ativo/Administrador.', 'Ative “Enviar relatório semanal” se aplicável e salve.'],
      utilizar: ['Crie usuários para quem precisa de acesso.', 'Revogue acesso de ex-colaboradores.'],
      praticas: ['Princípio do privilégio mínimo.', 'Revise permissões periodicamente.'],
      erros: ['Conceder permissões em excesso.', 'Compartilhar credenciais.'],
      faq: [{ q: 'Como dar acesso a um novo colaborador?', a: 'Crie o usuário e atribua o perfil de permissão necessário.' }],
      kpis: ['Segurança da informação', 'Conformidade de acesso'],
      responsavel: 'TI · Administrador do Sistema',
      imgs: [{ src: 'usuarios.png', cap: 'Cadastro de usuário — ativo, administrador, relatório, nome e e-mail.' }],
    }),
    F({
      id: 'testers', name: 'Testers',
      group: 'Controle de Acesso', journey: 'operar', role: 'TI', level: 'Intermediário',
      lead: 'Usuários com acesso a versões de teste antes do lançamento.',
      oque: 'Gerencia os testers do aplicativo — nome, e-mail e ativação — para validar novas versões em ambiente controlado.',
      quando: 'Para testar funcionalidades, correções ou atualizações antes do público final.',
      beneficios: ['Garante qualidade do app', 'Reduz erros em produção', 'Coleta de feedback antecipada'],
      prereq: ['Equipe ou usuários designados para teste.'],
      configurar: ['Acesse Controle de Acesso › Testers e clique em Adicionar.', 'Informe nome e e-mail do tester e ative.', 'Remova testers ao concluir os testes.'],
      utilizar: ['Forneça instruções de teste.', 'Colete feedback de forma estruturada.'],
      praticas: ['Defina um plano de testes claro.', 'Itere rápido com base no feedback.'],
      erros: ['Testar de forma insuficiente.', 'Não remover testers antigos.'],
      faq: [{ q: 'Como o tester recebe a versão?', a: 'Pelos canais de distribuição de teste configurados com a equipe Leanwork.' }],
      kpis: ['Qualidade do app', 'Bugs em produção'],
      responsavel: 'TI · QA',
      imgs: [{ src: 'testers.png', cap: 'Listagem de testers com nome e e-mail.' }],
    }),
    F({
      id: 'logs', name: 'Logs',
      group: 'Controle de Acesso', journey: 'acompanhar', role: 'TI', level: 'Intermediário',
      lead: 'Registro de todas as ações realizadas no painel — auditoria e segurança.',
      oque: 'Histórico detalhado de eventos do painel: usuário, método, mensagem e data de cada ação.',
      quando: 'Para auditar atividades, investigar problemas e rastrear alterações.',
      beneficios: ['Histórico completo das operações', 'Identificação da causa-raiz', 'Responsabilização das ações'],
      prereq: ['N/A — gerado automaticamente pelo sistema.'],
      configurar: ['Não há configuração direta — os logs são registrados automaticamente.'],
      utilizar: ['Acesse Controle de Acesso › Logs.', 'Use os filtros para buscar por usuário, data ou tipo de ação.', 'Analise usuário, método, mensagem e data.'],
      praticas: ['Revise os logs com regularidade.', 'Use-os no treinamento e na resolução de problemas.'],
      erros: ['Ignorar os logs.', 'Não monitorar eventos críticos.'],
      faq: [{ q: 'Posso exportar os logs?', a: 'Consulte o time Leanwork sobre exportação e política de retenção.' }],
      kpis: ['Segurança do sistema', 'Tempo de resolução'],
      responsavel: 'TI · Segurança da Informação',
      imgs: [{ src: 'logs.png', cap: 'Histórico de logs — usuário, método, mensagem e data de cada ação.' }],
    }),

    /* ===================== PRIVACIDADE & LGPD ===================== */
    F({
      id: 'lgpd', name: 'Solicitações de Exclusão',
      group: 'Privacidade & LGPD', journey: 'operar', role: 'Atendimento', level: 'Avançado',
      lead: 'Atendimento aos pedidos de exclusão de dados em conformidade com a LGPD.',
      oque: 'Gerencia com segurança os pedidos de exclusão de dados enviados pelos usuários — nome, e-mail, data da solicitação e status.',
      quando: 'Sempre que um usuário solicitar a remoção de seus dados pessoais.',
      beneficios: ['Conformidade com a LGPD', 'Confiança e respeito ao titular', 'Evita multas e sanções'],
      prereq: ['Processo interno de tratamento de solicitações definido.'],
      configurar: ['Acesse Privacidade & LGPD › Solicitações de Exclusão.', 'As solicitações recebidas aparecem na listagem com seu status.'],
      utilizar: ['Verifique a identidade do solicitante.', 'Processe a exclusão conforme a política e a lei.', 'Comunique a conclusão ao usuário.'],
      praticas: ['Tenha um processo claro e documentado.', 'Responda dentro do prazo legal.'],
      erros: ['Perder o prazo legal.', 'Exclusão incompleta de dados.'],
      faq: [{ q: 'Qual o prazo para atender?', a: 'Atenda dentro do prazo legal vigente e registre cada solicitação e a ação tomada.' }],
      kpis: ['Conformidade LGPD', 'Reclamações de privacidade'],
      responsavel: 'DPO · Jurídico · Atendimento',
      imgs: [{ src: 'solicitacoes-exclusao.png', cap: 'Listagem de solicitações de exclusão com status.' }],
    }),
  ];

  /* navegação espelhando o painel administrativo */
  const NAV = [
    { group: 'Painéis', items: ['dashboard', 'performance'] },
    { group: 'Marketing', items: ['vitrines', 'hotsites'] },
    {
      group: 'Configurações da Loja', items: ['categorias'],
      subs: [
        { name: 'Produtos', items: ['p-especificacoes', 'p-grades', 'p-etiquetas', 'p-selos', 'p-recomendacoes', 'p-restricoes'] },
      ],
      itemsAfter: ['assinaturas', 'integracoes'],
      subsAfter: [
        { name: 'Configurações', items: ['c-gerais', 'c-versao', 'c-redes', 'c-institucionais', 'c-servico', 'c-suporte'] },
      ],
    },
    { group: 'Controle de Acesso', items: ['usuarios', 'testers', 'logs'] },
    { group: 'Privacidade & LGPD', items: ['lgpd'] },
  ];

  const JOURNEY = [
    { id: 'configurar', n: '01', t: 'Configurar', d: 'Estruturar loja, catálogo, acessos e integrações.' },
    { id: 'operar', n: '02', t: 'Operar', d: 'Rotina diária: campanhas, vitrines e destaques.' },
    { id: 'acompanhar', n: '03', t: 'Acompanhar', d: 'Ler indicadores, performance e auditoria.' },
    { id: 'evoluir', n: '04', t: 'Evoluir', d: 'Boas práticas, novas versões e melhoria contínua.' },
  ];

  /* Primeiros passos — roteiro de implantação reutilizável para qualquer cliente.
     Sem vídeos: cada passo é uma tarefa objetiva que linka para a funcionalidade. */
  const START = [
    {
      id: 'configurar', n: '01', t: 'Configurar a loja', stage: 'configurar',
      goal: 'Deixar a base pronta: acessos, catálogo e integrações.',
      tasks: [
        { t: 'Criar os usuários da equipe e definir permissões', fid: 'usuarios' },
        { t: 'Revisar a árvore de Categorias (sincronizada da plataforma)', fid: 'categorias' },
        { t: 'Conferir Grades e Especificações dos produtos', fid: 'p-grades' },
        { t: 'Conectar as Integrações necessárias (pagamento, busca, logística)', fid: 'integracoes' },
        { t: 'Ajustar as Configurações Gerais (catálogo, checkout, produto)', fid: 'c-gerais' },
        { t: 'Preencher dados de Loja, Endereço e Suporte', fid: 'c-suporte' },
      ],
    },
    {
      id: 'operar', n: '02', t: 'Operar no dia a dia', stage: 'operar',
      goal: 'Publicar campanhas e manter a loja viva.',
      tasks: [
        { t: 'Publicar a primeira Vitrine com componentes', fid: 'vitrines' },
        { t: 'Criar um Hotsite para uma campanha específica', fid: 'hotsites' },
        { t: 'Aplicar Etiquetas e Selos nos produtos-chave', fid: 'p-selos' },
        { t: 'Configurar Recomendações de produtos', fid: 'p-recomendacoes' },
        { t: 'Definir Restrições de venda, se necessário', fid: 'p-restricoes' },
      ],
    },
    {
      id: 'acompanhar', n: '03', t: 'Acompanhar resultados', stage: 'acompanhar',
      goal: 'Ler indicadores e transformar dados em decisão.',
      tasks: [
        { t: 'Acompanhar o Dashboard diariamente', fid: 'dashboard' },
        { t: 'Analisar canais e funil em Performance', fid: 'performance' },
        { t: 'Auditar ações da equipe pelos Logs', fid: 'logs' },
      ],
    },
    {
      id: 'evoluir', n: '04', t: 'Evoluir com governança', stage: 'evoluir',
      goal: 'Manter o app atualizado e em conformidade.',
      tasks: [
        { t: 'Avisar novas versões pelo Controle de Versão', fid: 'c-versao' },
        { t: 'Validar novidades com Testers antes do público', fid: 'testers' },
        { t: 'Tratar Solicitações de Exclusão (LGPD) no prazo', fid: 'lgpd' },
        { t: 'Revisar Páginas Institucionais e de Serviço', fid: 'c-institucionais' },
      ],
    },
  ];

  const FAQ = [
    { cat: 'Acesso', q: 'Como faço meu primeiro login?', a: 'Use o e-mail cadastrado e a senha enviada pela Leanwork. No primeiro acesso o sistema solicita a troca de senha.' },
    { cat: 'Acesso', q: 'Esqueci minha senha. E agora?', a: 'Use “Esqueci minha senha” na tela de login ou peça a um Administrador para redefinir em Controle de Acesso › Usuários.' },
    { cat: 'Acesso', q: 'Como dou acesso a um novo colaborador?', a: 'Em Controle de Acesso › Usuários, crie o usuário e atribua o perfil de permissão mínimo necessário.' },
    { cat: 'Dados', q: 'Os dados do dashboard são em tempo real?', a: 'Sim. Os indicadores são atualizados continuamente; use os filtros de período para recortes específicos.' },
    { cat: 'Catálogo', q: 'Qual a diferença entre Categorias, Etiquetas e Selos?', a: 'Categorias organizam a navegação (hierarquia); etiquetas destacam campanhas no card; selos são marcadores visuais sobre o produto.' },
    { cat: 'Catálogo', q: 'Posso ter mais de uma grade no mesmo produto?', a: 'Sim — por exemplo Tamanho e Cor simultaneamente. Configure cada grade e associe às categorias.' },
    { cat: 'Marketing', q: 'Posso agendar uma vitrine para o futuro?', a: 'Sim, definindo as datas de início e término no cadastro da vitrine.' },
    { cat: 'Integrações', q: 'Quais sistemas posso integrar?', a: 'Pagamento, analytics, logística, busca, mídia e avaliações. Consulte o time Leanwork para o catálogo atualizado.' },
    { cat: 'LGPD', q: 'Qual o prazo para uma solicitação de exclusão?', a: 'Atenda dentro do prazo legal vigente. Registre cada solicitação e a ação tomada em Privacidade & LGPD.' },
    { cat: 'Suporte', q: 'Como falo com a Leanwork?', a: 'Pelo seu CSM dedicado e pelos canais oficiais. Os contatos ficam também na seção Suporte deste guia.' },
  ];

  const LEVELS = { Essencial: 1, 'Básico': 1, 'Intermediário': 2, 'Avançado': 3 };

  /* Gestão: Lean App × sua plataforma de e-commerce — orientação fundamental.
     Conteúdo 100% genérico: nunca cite plataformas, ferramentas ou clientes específicos. */
  const GESTAO = {
    intro: 'A experiência do seu aplicativo é sustentada por dois ambientes que trabalham juntos. No painel da Lean App você gerencia a vitrine e a experiência do app — campanhas, banners, hotsites, selos e performance. Já a sua plataforma de e-commerce continua sendo a base de dados central: catálogo, preços, clientes e pedidos são sincronizados automaticamente para o app via API. Entender essa divisão ajuda seu time a saber exatamente onde realizar cada ajuste.',
    cols: [
      {
        key: 'lean',
        title: 'Painel Lean App',
        tag: 'Você gerencia diretamente',
        desc: 'A vitrine e a experiência do app.',
        items: [
          'Vitrines e banners — com possibilidade de agendar campanhas',
          'Hotsites (landing pages)',
          'Selos e tags de produto — com possibilidade de agendar campanhas',
          'Performance: analytics, conversões e vendas dos canais',
          'Categorias — ajustes ocasionais, quando há mudanças',
          'Configurações de catálogo, carrinho/checkout e produto — ajustes raros',
        ],
      },
      {
        key: 'plataforma',
        title: 'Sua plataforma de e-commerce',
        tag: 'Sincronizado via API · gerido na plataforma',
        desc: 'A base de dados central da operação.',
        items: [
          'Catálogo de produtos e preços',
          'Cupons e promoções',
          'Configurações de logística (opções de entrega)',
          'Configurações de pagamento (base)',
          'Autenticação do cliente',
          'Dados do cliente (perfil, endereços e pedidos)',
        ],
      },
    ],
    freq: [
      { level: 'Frequente', cls: 'high', note: 'No dia a dia', items: 'Vitrines e banners, hotsites, selos e tags de produto, performance.' },
      { level: 'Ocasional', cls: 'mid', note: 'Quando há mudanças', items: 'Categorias.' },
      { level: 'Raro', cls: 'low', note: 'Ajustes pontuais', items: 'Configurações de catálogo (layout, ordenação), carrinho/checkout e produto.' },
    ],
    tech: {
      kicker: 'Configuração técnica · Backend ⟷ plataforma',
      title: 'Etapas conjuntas na integração',
      lead: 'Estes dois pontos envolvem uma etapa técnica conjunta entre o backend e a sua plataforma — vale mapeá-los logo no início.',
      items: [
        {
          t: 'Meios de pagamento',
          d: 'Alguns meios de pagamento exigem configurações específicas no envio das informações (criptografia, tokenização, etc.). Esses métodos exigem integração no backend. Portanto, é importante ter mapeado e testado as formas de pagamento que poderão ser utilizadas, para que as configurações necessárias sejam implementadas na solução.',
          badges: {
            title: 'O que já está integrado?',
            items: ['Boleto', 'Cartão Adyen', 'Cartão Mercado Pago', 'Cartões que não exigem criptografia e/ou tokenização', 'PIX à vista'],
          },
        },
        {
          t: 'Envio de push notifications',
          d: 'O envio de notificações é realizado através do Firebase, por onde é possível fazer o disparo para ambas as plataformas (iOS e Android). Também é possível segmentar por audiências (criadas de forma antecipada), agendar envios, incluir imagens e deeplinks que direcionam o cliente para uma seção específica do aplicativo, e definir eventos de conversão (add_to_cart, purchase, etc.). O envio de notificações é ilimitado e o desempenho pode ser acompanhado pelo próprio painel do Firebase.',
        },
      ],
    },
  };

  window.LA = {
    FEATURES, NAV, JOURNEY, START, FAQ, LEVELS, GESTAO,
    byId: (id) => FEATURES.find((f) => f.id === id),
    byJourney: (j) => FEATURES.filter((f) => f.journey === j),
    GROUPS: ['Painéis', 'Marketing', 'Configurações da Loja', 'Controle de Acesso', 'Privacidade & LGPD'],
  };
})();
